export enum TYPE_REPORT {
  HABILITACION = 'HABILITACION ',
  ADD = 'ADD',
  REMOVE = 'REMOVE',
  ASSIGNMENT = 'ASSIGNMENT',
  DISCHARGE = 'DISCHARGE',
  ADMISSION = 'ADMISSION',
  MAINTENANCE = 'MAINTENANCE',

}
export enum STATUS_REPORT {
  PEDING = 'PEDING',
  AUTHORIZATED = 'AUTHORIZATED',
  REJECTED = 'REJECTED',
}